//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieMatrix.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieMatrix.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acting.
        /// </summary>
        public static string Acting {
            get {
                return ResourceManager.GetString("Acting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action &amp; Adventure.
        /// </summary>
        public static string Action_Adventure {
            get {
                return ResourceManager.GetString("Action_Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Watchlist.
        /// </summary>
        public static string AddWatchlist {
            get {
                return ResourceManager.GetString("AddWatchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Your List.
        /// </summary>
        public static string AddYourList {
            get {
                return ResourceManager.GetString("AddYourList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Your List first to change!.
        /// </summary>
        public static string AddYourListToChange {
            get {
                return ResourceManager.GetString("AddYourListToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        public static string Adventure {
            get {
                return ResourceManager.GetString("Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airing This Week.
        /// </summary>
        public static string AiringThisWeek {
            get {
                return ResourceManager.GetString("AiringThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airing Today.
        /// </summary>
        public static string AiringToday {
            get {
                return ResourceManager.GetString("AiringToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Genres.
        /// </summary>
        public static string AllGenres {
            get {
                return ResourceManager.GetString("AllGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of.
        /// </summary>
        public static string AllOf {
            get {
                return ResourceManager.GetString("AllOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation.
        /// </summary>
        public static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any of.
        /// </summary>
        public static string AnyOf {
            get {
                return ResourceManager.GetString("AnyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquarius.
        /// </summary>
        public static string Aquarius {
            get {
                return ResourceManager.GetString("Aquarius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aries.
        /// </summary>
        public static string Aries {
            get {
                return ResourceManager.GetString("Aries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art.
        /// </summary>
        public static string Art {
            get {
                return ResourceManager.GetString("Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awards.
        /// </summary>
        public static string Awards {
            get {
                return ResourceManager.GetString("Awards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backdrops.
        /// </summary>
        public static string Backdrops {
            get {
                return ResourceManager.GetString("Backdrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancer.
        /// </summary>
        public static string Cancer {
            get {
                return ResourceManager.GetString("Cancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capricorn.
        /// </summary>
        public static string Capricorn {
            get {
                return ResourceManager.GetString("Capricorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card View.
        /// </summary>
        public static string CardView {
            get {
                return ResourceManager.GetString("CardView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification.
        /// </summary>
        public static string Certification {
            get {
                return ResourceManager.GetString("Certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Names.
        /// </summary>
        public static string CheckNames {
            get {
                return ResourceManager.GetString("CheckNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file and directory names in the folder are listed below. The &apos;Name&apos; column will be used while searching, you can correct the wrong ones..
        /// </summary>
        public static string CheckNamesHelp {
            get {
                return ResourceManager.GetString("CheckNamesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chooser.
        /// </summary>
        public static string ColumnChooser {
            get {
                return ResourceManager.GetString("ColumnChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        public static string Comedy {
            get {
                return ResourceManager.GetString("Comedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew.
        /// </summary>
        public static string Crew {
            get {
                return ResourceManager.GetString("Crew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crime.
        /// </summary>
        public static string Crime {
            get {
                return ResourceManager.GetString("Crime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        public static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        public static string DateAdded {
            get {
                return ResourceManager.GetString("DateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Updated.
        /// </summary>
        public static string DateUpdated {
            get {
                return ResourceManager.GetString("DateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deathday.
        /// </summary>
        public static string Deathday {
            get {
                return ResourceManager.GetString("Deathday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Purple.
        /// </summary>
        public static string DeepPurple {
            get {
                return ResourceManager.GetString("DeepPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default View.
        /// </summary>
        public static string DefaultView {
            get {
                return ResourceManager.GetString("DefaultView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directing.
        /// </summary>
        public static string Directing {
            get {
                return ResourceManager.GetString("Directing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        public static string Director {
            get {
                return ResourceManager.GetString("Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover Movies.
        /// </summary>
        public static string DiscoverMovies {
            get {
                return ResourceManager.GetString("DiscoverMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover TV Shows.
        /// </summary>
        public static string DiscoverTvShows {
            get {
                return ResourceManager.GetString("DiscoverTvShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentary.
        /// </summary>
        public static string Documentary {
            get {
                return ResourceManager.GetString("Documentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        public static string Drama {
            get {
                return ResourceManager.GetString("Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended.
        /// </summary>
        public static string Ended {
            get {
                return ResourceManager.GetString("Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode.
        /// </summary>
        public static string Episode {
            get {
                return ResourceManager.GetString("Episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episodes.
        /// </summary>
        public static string Episodes {
            get {
                return ResourceManager.GetString("Episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application error occured !.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File.
        /// </summary>
        public static string ExcelFile {
            get {
                return ResourceManager.GetString("ExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Options.
        /// </summary>
        public static string ExportOptions {
            get {
                return ResourceManager.GetString("ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasy.
        /// </summary>
        public static string Fantasy {
            get {
                return ResourceManager.GetString("Fantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Cast.
        /// </summary>
        public static string FeaturedCast {
            get {
                return ResourceManager.GetString("FeaturedCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Crew.
        /// </summary>
        public static string FeaturedCrew {
            get {
                return ResourceManager.GetString("FeaturedCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Editor.
        /// </summary>
        public static string FilterEditor {
            get {
                return ResourceManager.GetString("FilterEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Air Date.
        /// </summary>
        public static string FirstAirDate {
            get {
                return ResourceManager.GetString("FirstAirDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Air Date 🠅.
        /// </summary>
        public static string FirstAirDateAsc {
            get {
                return ResourceManager.GetString("FirstAirDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Air Date 🠇.
        /// </summary>
        public static string FirstAirDateDesc {
            get {
                return ResourceManager.GetString("FirstAirDateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Cast.
        /// </summary>
        public static string FullCast {
            get {
                return ResourceManager.GetString("FullCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Crew.
        /// </summary>
        public static string FullCrew {
            get {
                return ResourceManager.GetString("FullCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemini.
        /// </summary>
        public static string Gemini {
            get {
                return ResourceManager.GetString("Gemini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than.
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header here to group by that column.
        /// </summary>
        public static string GroupPanelDragText {
            get {
                return ResourceManager.GetString("GroupPanelDragText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Stars.
        /// </summary>
        public static string GuestStars {
            get {
                return ResourceManager.GetString("GuestStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Column Chooser.
        /// </summary>
        public static string HideColumnChooser {
            get {
                return ResourceManager.GetString("HideColumnChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        public static string Horror {
            get {
                return ResourceManager.GetString("Horror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr..
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Gallery.
        /// </summary>
        public static string ImageGallery {
            get {
                return ResourceManager.GetString("ImageGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDb.
        /// </summary>
        public static string IMDb {
            get {
                return ResourceManager.GetString("IMDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDb Rating.
        /// </summary>
        public static string IMDbRating {
            get {
                return ResourceManager.GetString("IMDbRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDb Top 250.
        /// </summary>
        public static string IMDbTop250 {
            get {
                return ResourceManager.GetString("IMDbTop250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDb Top 250 Movies.
        /// </summary>
        public static string IMDbTop250Movies {
            get {
                return ResourceManager.GetString("IMDbTop250Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDb Top 250 TV Shows.
        /// </summary>
        public static string IMDbTop250TVShows {
            get {
                return ResourceManager.GetString("IMDbTop250TVShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDb Top Rating.
        /// </summary>
        public static string IMDbTopRating {
            get {
                return ResourceManager.GetString("IMDbTopRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDb Votes.
        /// </summary>
        public static string IMDbVotes {
            get {
                return ResourceManager.GetString("IMDbVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Wizard.
        /// </summary>
        public static string ImportWizard {
            get {
                return ResourceManager.GetString("ImportWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard takes you through to the steps required to import movies, tv shows or people from a folder or Excel file. To continue, select data type and folder/file path and click Next..
        /// </summary>
        public static string ImportWizardHelp {
            get {
                return ResourceManager.GetString("ImportWizardHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        public static string Include {
            get {
                return ResourceManager.GetString("Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        public static string Indigo {
            get {
                return ResourceManager.GetString("Indigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Production.
        /// </summary>
        public static string InProduction {
            get {
                return ResourceManager.GetString("InProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Your List.
        /// </summary>
        public static string InYourList {
            get {
                return ResourceManager.GetString("InYourList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Between.
        /// </summary>
        public static string IsBetween {
            get {
                return ResourceManager.GetString("IsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is in year.
        /// </summary>
        public static string IsInYear {
            get {
                return ResourceManager.GetString("IsInYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kids.
        /// </summary>
        public static string Kids {
            get {
                return ResourceManager.GetString("Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known For.
        /// </summary>
        public static string KnownFor {
            get {
                return ResourceManager.GetString("KnownFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Air Date.
        /// </summary>
        public static string LastAirDate {
            get {
                return ResourceManager.GetString("LastAirDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leo.
        /// </summary>
        public static string Leo {
            get {
                return ResourceManager.GetString("Leo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than.
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libra.
        /// </summary>
        public static string Libra {
            get {
                return ResourceManager.GetString("Libra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Blue.
        /// </summary>
        public static string LightBlue {
            get {
                return ResourceManager.GetString("LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting.
        /// </summary>
        public static string Lighting {
            get {
                return ResourceManager.GetString("Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List View.
        /// </summary>
        public static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Operations.
        /// </summary>
        public static string LoadingOperations {
            get {
                return ResourceManager.GetString("LoadingOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Files.
        /// </summary>
        public static string LocalFiles {
            get {
                return ResourceManager.GetString("LocalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Folder.
        /// </summary>
        public static string LocalFolder {
            get {
                return ResourceManager.GetString("LocalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Favorite.
        /// </summary>
        public static string MarkFavorite {
            get {
                return ResourceManager.GetString("MarkFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Seen.
        /// </summary>
        public static string MarkSeen {
            get {
                return ResourceManager.GetString("MarkSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Rating.
        /// </summary>
        public static string MinimumRating {
            get {
                return ResourceManager.GetString("MinimumRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Votes.
        /// </summary>
        public static string MinimumVotes {
            get {
                return ResourceManager.GetString("MinimumVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min..
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Genres.
        /// </summary>
        public static string MovieGenres {
            get {
                return ResourceManager.GetString("MovieGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Movies &amp; TV Shows &amp; People.
        /// </summary>
        public static string MultiSearch {
            get {
                return ResourceManager.GetString("MultiSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My List.
        /// </summary>
        public static string MyList {
            get {
                return ResourceManager.GetString("MyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Movie List.
        /// </summary>
        public static string MyMovieList {
            get {
                return ResourceManager.GetString("MyMovieList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My People List.
        /// </summary>
        public static string MyPeopleList {
            get {
                return ResourceManager.GetString("MyPeopleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery.
        /// </summary>
        public static string Mystery {
            get {
                return ResourceManager.GetString("Mystery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My TV Show List.
        /// </summary>
        public static string MyTVShowList {
            get {
                return ResourceManager.GetString("MyTVShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Name.
        /// </summary>
        public static string NativeName {
            get {
                return ResourceManager.GetString("NativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networks.
        /// </summary>
        public static string Networks {
            get {
                return ResourceManager.GetString("Networks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networks &amp; Companies.
        /// </summary>
        public static string NetworksCompanies {
            get {
                return ResourceManager.GetString("NetworksCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novel.
        /// </summary>
        public static string Novel {
            get {
                return ResourceManager.GetString("Novel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Playing.
        /// </summary>
        public static string NowPlaying {
            get {
                return ResourceManager.GetString("NowPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Playing Movies.
        /// </summary>
        public static string NowPlayingMovies {
            get {
                return ResourceManager.GetString("NowPlayingMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Episodes.
        /// </summary>
        public static string NumberOfEpisodes {
            get {
                return ResourceManager.GetString("NumberOfEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Seasons.
        /// </summary>
        public static string NumberOfSeasons {
            get {
                return ResourceManager.GetString("NumberOfSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Language.
        /// </summary>
        public static string OriginalLanguage {
            get {
                return ResourceManager.GetString("OriginalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Name.
        /// </summary>
        public static string OriginalName {
            get {
                return ResourceManager.GetString("OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Size.
        /// </summary>
        public static string OriginalSize {
            get {
                return ResourceManager.GetString("OriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Title.
        /// </summary>
        public static string OriginalTitle {
            get {
                return ResourceManager.GetString("OriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscar Winners.
        /// </summary>
        public static string OscarWinners {
            get {
                return ResourceManager.GetString("OscarWinners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscar Winning Movies.
        /// </summary>
        public static string OscarWinningMovies {
            get {
                return ResourceManager.GetString("OscarWinningMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Folder.
        /// </summary>
        public static string ParentFolder {
            get {
                return ResourceManager.GetString("ParentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of.
        /// </summary>
        public static string Partof {
            get {
                return ResourceManager.GetString("Partof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People &amp; Companies.
        /// </summary>
        public static string PeopleCompanies {
            get {
                return ResourceManager.GetString("PeopleCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Rating.
        /// </summary>
        public static string PersonalRating {
            get {
                return ResourceManager.GetString("PersonalRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot.
        /// </summary>
        public static string Pilot {
            get {
                return ResourceManager.GetString("Pilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pisces.
        /// </summary>
        public static string Pisces {
            get {
                return ResourceManager.GetString("Pisces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Birth.
        /// </summary>
        public static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        public static string Planned {
            get {
                return ResourceManager.GetString("Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Trailer.
        /// </summary>
        public static string PlayTrailer {
            get {
                return ResourceManager.GetString("PlayTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string Popular {
            get {
                return ResourceManager.GetString("Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity.
        /// </summary>
        public static string Popularity {
            get {
                return ResourceManager.GetString("Popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity 🠅.
        /// </summary>
        public static string PopularityAsc {
            get {
                return ResourceManager.GetString("PopularityAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity 🠇.
        /// </summary>
        public static string PopularityDesc {
            get {
                return ResourceManager.GetString("PopularityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Movies.
        /// </summary>
        public static string PopularMovies {
            get {
                return ResourceManager.GetString("PopularMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular People.
        /// </summary>
        public static string PopularPeople {
            get {
                return ResourceManager.GetString("PopularPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular TV Shows.
        /// </summary>
        public static string PopularTVShows {
            get {
                return ResourceManager.GetString("PopularTVShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posters.
        /// </summary>
        public static string Posters {
            get {
                return ResourceManager.GetString("Posters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Production.
        /// </summary>
        public static string PostProduction {
            get {
                return ResourceManager.GetString("PostProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        public static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Companies.
        /// </summary>
        public static string ProductionCompanies {
            get {
                return ResourceManager.GetString("ProductionCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Countries.
        /// </summary>
        public static string ProductionCountries {
            get {
                return ResourceManager.GetString("ProductionCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reality.
        /// </summary>
        public static string Reality {
            get {
                return ResourceManager.GetString("Reality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh All.
        /// </summary>
        public static string RefreshAll {
            get {
                return ResourceManager.GetString("RefreshAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to refresh all items in your list?.
        /// </summary>
        public static string RefreshAllConfirm {
            get {
                return ResourceManager.GetString("RefreshAllConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to refresh selected items in your list?.
        /// </summary>
        public static string RefreshSelectedConfirm {
            get {
                return ResourceManager.GetString("RefreshSelectedConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released.
        /// </summary>
        public static string Released {
            get {
                return ResourceManager.GetString("Released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date 🠅.
        /// </summary>
        public static string ReleaseDateAsc {
            get {
                return ResourceManager.GetString("ReleaseDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date 🠇.
        /// </summary>
        public static string ReleaseDateDesc {
            get {
                return ResourceManager.GetString("ReleaseDateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove it from your list?.
        /// </summary>
        public static string RemoveConfirm {
            get {
                return ResourceManager.GetString("RemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from My List.
        /// </summary>
        public static string RemoveMyList {
            get {
                return ResourceManager.GetString("RemoveMyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the selected items from your list?.
        /// </summary>
        public static string RemoveSelectedConfirm {
            get {
                return ResourceManager.GetString("RemoveSelectedConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning Series.
        /// </summary>
        public static string ReturningSeries {
            get {
                return ResourceManager.GetString("ReturningSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue 🠅.
        /// </summary>
        public static string RevenueAsc {
            get {
                return ResourceManager.GetString("RevenueAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue 🠇.
        /// </summary>
        public static string RevenueDesc {
            get {
                return ResourceManager.GetString("RevenueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance.
        /// </summary>
        public static string Romance {
            get {
                return ResourceManager.GetString("Romance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumored.
        /// </summary>
        public static string Rumored {
            get {
                return ResourceManager.GetString("Rumored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        public static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagittarius.
        /// </summary>
        public static string Sagittarius {
            get {
                return ResourceManager.GetString("Sagittarius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sci-Fi &amp; Fantasy.
        /// </summary>
        public static string Sci_Fi_Fantasy {
            get {
                return ResourceManager.GetString("Sci_Fi_Fantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science Fiction.
        /// </summary>
        public static string Science_Fiction {
            get {
                return ResourceManager.GetString("Science_Fiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorpio.
        /// </summary>
        public static string Scorpio {
            get {
                return ResourceManager.GetString("Scorpio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenplay.
        /// </summary>
        public static string Screenplay {
            get {
                return ResourceManager.GetString("Screenplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenstory.
        /// </summary>
        public static string Screenstory {
            get {
                return ResourceManager.GetString("Screenstory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By File.
        /// </summary>
        public static string SearchByFile {
            get {
                return ResourceManager.GetString("SearchByFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchBy IMDb Id.
        /// </summary>
        public static string SearchByImdbId {
            get {
                return ResourceManager.GetString("SearchByImdbId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Name.
        /// </summary>
        public static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Subtitles.
        /// </summary>
        public static string SearchSubtitles {
            get {
                return ResourceManager.GetString("SearchSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string Seasons {
            get {
                return ResourceManager.GetString("Seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen.
        /// </summary>
        public static string Seen {
            get {
                return ResourceManager.GetString("Seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Columns.
        /// </summary>
        public static string SelectColumns {
            get {
                return ResourceManager.GetString("SelectColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which column in the file corresponds to what information and click Next. The &apos;Name&apos; column will be used while searching and must be selected. It may contain names (e.g The Godfather, Marlon Brando) or IMDb identifiers (e.g tt0068646, nm0000008)..
        /// </summary>
        public static string SelectColumnsHelp {
            get {
                return ResourceManager.GetString("SelectColumnsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select items you want to add.
        /// </summary>
        public static string SelectYouWantToAdd {
            get {
                return ResourceManager.GetString("SelectYouWantToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search results are shown at right-most. Select items you want to add to your list and click Next. You can change them if there are more than one result..
        /// </summary>
        public static string SelectYouWantToAddHelp {
            get {
                return ResourceManager.GetString("SelectYouWantToAddHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Column Chooser.
        /// </summary>
        public static string ShowColumnChooser {
            get {
                return ResourceManager.GetString("ShowColumnChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        public static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soap.
        /// </summary>
        public static string Soap {
            get {
                return ResourceManager.GetString("Soap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starring.
        /// </summary>
        public static string Starring {
            get {
                return ResourceManager.GetString("Starring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story.
        /// </summary>
        public static string Story {
            get {
                return ResourceManager.GetString("Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagline.
        /// </summary>
        public static string Tagline {
            get {
                return ResourceManager.GetString("Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk.
        /// </summary>
        public static string Talk {
            get {
                return ResourceManager.GetString("Talk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taurus.
        /// </summary>
        public static string Taurus {
            get {
                return ResourceManager.GetString("Taurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thriller.
        /// </summary>
        public static string Thriller {
            get {
                return ResourceManager.GetString("Thriller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMDB.
        /// </summary>
        public static string TMDB {
            get {
                return ResourceManager.GetString("TMDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMDB Rating.
        /// </summary>
        public static string TMDBRating {
            get {
                return ResourceManager.GetString("TMDBRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMDB Votes.
        /// </summary>
        public static string TMDBVotes {
            get {
                return ResourceManager.GetString("TMDBVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Movie.
        /// </summary>
        public static string TV_Movie {
            get {
                return ResourceManager.GetString("TV_Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Show Genres.
        /// </summary>
        public static string TvShowGenres {
            get {
                return ResourceManager.GetString("TvShowGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows.
        /// </summary>
        public static string TVShows {
            get {
                return ResourceManager.GetString("TVShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows Airing This Week.
        /// </summary>
        public static string TVShowsAiringThisWeek {
            get {
                return ResourceManager.GetString("TVShowsAiringThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows Airing Today.
        /// </summary>
        public static string TVShowsAiringToday {
            get {
                return ResourceManager.GetString("TVShowsAiringToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming.
        /// </summary>
        public static string Upcoming {
            get {
                return ResourceManager.GetString("Upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Movies.
        /// </summary>
        public static string UpcomingMovies {
            get {
                return ResourceManager.GetString("UpcomingMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Video / Image File Names.
        /// </summary>
        public static string UseFileNames {
            get {
                return ResourceManager.GetString("UseFileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Parent Folder Names.
        /// </summary>
        public static string UseParentFolderNames {
            get {
                return ResourceManager.GetString("UseParentFolderNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Totals.
        /// </summary>
        public static string ViewTotals {
            get {
                return ResourceManager.GetString("ViewTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virgo.
        /// </summary>
        public static string Virgo {
            get {
                return ResourceManager.GetString("Virgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMDB Rating 🠅.
        /// </summary>
        public static string VoteAverageAsc {
            get {
                return ResourceManager.GetString("VoteAverageAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMDB Rating 🠇.
        /// </summary>
        public static string VoteAverageDesc {
            get {
                return ResourceManager.GetString("VoteAverageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes.
        /// </summary>
        public static string Votes {
            get {
                return ResourceManager.GetString("Votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War.
        /// </summary>
        public static string War {
            get {
                return ResourceManager.GetString("War", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War &amp; Politics.
        /// </summary>
        public static string War_Politics {
            get {
                return ResourceManager.GetString("War_Politics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchlist.
        /// </summary>
        public static string Watchlist {
            get {
                return ResourceManager.GetString("Watchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western.
        /// </summary>
        public static string Western {
            get {
                return ResourceManager.GetString("Western", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing the wizard.
        /// </summary>
        public static string WizardComplete {
            get {
                return ResourceManager.GetString("WizardComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully completed the wizard. Click &apos;Finish&apos; to add items below to your list..
        /// </summary>
        public static string WizardCompleteHelp {
            get {
                return ResourceManager.GetString("WizardCompleteHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer.
        /// </summary>
        public static string Writer {
            get {
                return ResourceManager.GetString("Writer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing.
        /// </summary>
        public static string Writing {
            get {
                return ResourceManager.GetString("Writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
